services:
  sentiment-api:
    build: .
    container_name: sentiment-analysis-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./datasets:/app/datasets
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
